/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuditLogEntry = IDL.Record({
  'status' : IDL.Text,
  'side' : IDL.Text,
  'alertId' : IDL.Text,
  'receivedAt' : IDL.Int,
  'timestamp' : IDL.Text,
  'signal' : IDL.Text,
  'symbol' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearBinanceCredentials' : IDL.Func([], [], []),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultOrderQuantity' : IDL.Func([], [IDL.Text], ['query']),
  'getKillSwitchStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getTestnetMode' : IDL.Func([], [IDL.Bool], ['query']),
  'hasBinanceCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  'hasWebhookSecret' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveWebhook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'setBinanceCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setDefaultOrderQuantity' : IDL.Func([IDL.Text], [], []),
  'setKillSwitch' : IDL.Func([IDL.Bool], [], []),
  'setTestnetMode' : IDL.Func([IDL.Bool], [], []),
  'setWebhookSecret' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuditLogEntry = IDL.Record({
    'status' : IDL.Text,
    'side' : IDL.Text,
    'alertId' : IDL.Text,
    'receivedAt' : IDL.Int,
    'timestamp' : IDL.Text,
    'signal' : IDL.Text,
    'symbol' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearBinanceCredentials' : IDL.Func([], [], []),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultOrderQuantity' : IDL.Func([], [IDL.Text], ['query']),
    'getKillSwitchStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getTestnetMode' : IDL.Func([], [IDL.Bool], ['query']),
    'hasBinanceCredentials' : IDL.Func([], [IDL.Bool], ['query']),
    'hasWebhookSecret' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveWebhook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'setBinanceCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setDefaultOrderQuantity' : IDL.Func([IDL.Text], [], []),
    'setKillSwitch' : IDL.Func([IDL.Bool], [], []),
    'setTestnetMode' : IDL.Func([IDL.Bool], [], []),
    'setWebhookSecret' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };