/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLogEntry {
  'status' : string,
  'side' : string,
  'alertId' : string,
  'receivedAt' : bigint,
  'timestamp' : string,
  'signal' : string,
  'symbol' : string,
  'reason' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearBinanceCredentials' : ActorMethod<[], undefined>,
  'getAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultOrderQuantity' : ActorMethod<[], string>,
  'getKillSwitchStatus' : ActorMethod<[], boolean>,
  'getTestnetMode' : ActorMethod<[], boolean>,
  'hasBinanceCredentials' : ActorMethod<[], boolean>,
  'hasWebhookSecret' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'receiveWebhook' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'setBinanceCredentials' : ActorMethod<[string, string], undefined>,
  'setDefaultOrderQuantity' : ActorMethod<[string], undefined>,
  'setKillSwitch' : ActorMethod<[boolean], undefined>,
  'setTestnetMode' : ActorMethod<[boolean], undefined>,
  'setWebhookSecret' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];